In [2]:
import tensorflow as tf

In [6]:
# Tensores

# Escaleres 
a = tf.constant(5)
b = tf.constant(3)
print("Escalar a:", a)

Escalar a: tf.Tensor(5, shape=(), dtype=int32)


In [7]:
# Vectores
v = tf.constant([5, 3, 8, 2])
print("Vector v:", v)

Vector v: tf.Tensor([5 3 8 2], shape=(4,), dtype=int32)


In [8]:
# Matrices
m = tf.constant([[5, 3, 8],
                 [2, 4, 1],
                 [7, 9, 6]])
print("Matriz m:\n", m)

Matriz m:
 tf.Tensor(
[[5 3 8]
 [2 4 1]
 [7 9 6]], shape=(3, 3), dtype=int32)


In [9]:
# 3D Tensores
t = tf.constant([[[5, 3, 8],
                  [2, 4, 1]],
                    [[7, 9, 6],
                    [0, 2, 4]]])
print("3D Tensor t:\n", t)

3D Tensor t:
 tf.Tensor(
[[[5 3 8]
  [2 4 1]]

 [[7 9 6]
  [0 2 4]]], shape=(2, 2, 3), dtype=int32)
